<?php

return [
    'about' => '<p>Soulmaz Taghavi es Socia y Cofundadora de Novo Taghavi, ubicada en Richmond, Virginia, en donde su práctica se enfocó en la Ley de Inmigración, Defensa Criminal y de Tráfico, y Ley Familiar. Soulmaz dedica la mayor parte de su práctica a todas las áreas de la Ley de Inmigración, con un enfoque en la defensa de expulsión. Soulmaz es una abogada dedicada, apasionada y agresiva con vasta experiencia en la representación de clientes en asuntos criminales y de tráfico en varios condados a través de la Comunidad de Virginia. Con su experiencia, Soulmaz entiende las consecuencias de la inmigración de las disposiciones criminales y del tráfico en Virginia.</p>
            <p>La familia de Soulmaz emigró a los Estados Unidos desde Irán en 1980, lo que en parte ayudó a cultivar su deseo de usar su educación para ayudar a individuos y familias a navegar nuestro sistema legal de manera eficiente y eficaz. Soulmaz se graduó con honores de la Facultad de Derecho de la Universidad Central de Durham en Carolina del Norte. Soulmaz, que es nativa de Richmond, obtuvo su licenciatura en Relaciones Internacionales y Economía de la Universidad Commonwealth Virginia y posteriormente obtuvo una maestría en Estudios de Oriente Medio de la Universidad de Virginia. Soulmaz también pasó un verano en el extranjero en una universidad en El Cairo, Egipto, donde estudió árabe y negocio internacional.</p>
            <p>Durante la escuela de derecho, Soulmaz sirvió como empleada estudiantil para el Honorable Juez Herbert B. Dixon, Jr., mientras que él presidió el Calendario de Delito Mayor en la Corte Superior del Distrito de Columbia en Washington, D.C. También sirvió como abogada estudiantil en la clínica de defensa penal, donde representaba a personas que habían sido acusadas de delitos menores. Mientras era una estudiante, Soulmaz también tuvo la rara distinción de publicar un artículo académico. Su propuesta, “Montes-López v. Holder: Aplicación de la Tercera Edad para asegurar un Derecho como tal para inmigrantes indigentes en procedimientos de expulsión”, la cual fue publicada en mayo de 2014.</p>
            <p>Antes de unirse a su socio Raúl Novo, Soulmaz trabajó durante casi tres años en la oficina de Fayad Law, en Richmond, Virginia. En la actualidad, Soulmaz tiene una grandiosa experiencia en la preparación y presentación de medidas de asistencia defensiva y peticiones ante los Tribunales de Inmigración y la Junta de Apelaciones de Inmigración, incluyendo Asilo, Cancelación de Retiro, Solicitud de Discreción Fiscal, Convención contra Tortura, 1-212(h) Crimen y Exenciones de Inadmisibilidad, y I-601A/I-601 Exenciones Provisionales. Soulmaz ha representado a individuos en Particular, Calendario Maestro y Audiencias de Bonos ante diferentes Tribunales de Inmigración. Tiene experiencia en la preparación y presentación de solicitudes de inmigración humanitaria y familiar, solicitudes, informes y exenciones para USCIS, incluyendo las solicitudes de naturalización y ajuste en los estados aplicaciones. Aisladamente dio argumentos orales ante un juez de tres tribunales de la Corte de Apelaciones de los Estados Unidos para el Cuarto Circuito, argumentando por los derechos legales de proceso en un supuesto caso de fraude de matrimonio de inmigración en Bassam Hanna contra Loretta Lynch el 21 de marzo de 2016.</p>
            Soulmaz es miembro de las Asociaciones de Abogados de Virginia y del Distrito de Columbia.',
    'img' => asset('img/mejor-abogado-en-chesterfield.webp'),
    'img_alt' => 'Mejor abogado en chesterfield',
    'member1' => 'Asociación de Abogados de Virginia',
    'member2' => 'Colegio de Abogados del Distrito de Columbia',
    'member3' => 'Asociación Iraní-Americana de Abogados (Capítulo D.C.)',
    'member4' => 'Asociación Americana de Abogados de Inmigración',
    'member5' => 'Central Virginia Sociedad Iraní Americana (Tesorera)',
];