<?php

return [
    'about' => '<p>Soulmaz Taghavi is a Partner and Co-Founder of Novo Taghavi, located in Richmond, Virginia where her practice expands Immigration Law, Criminal & Traffic Defense and Family Law. Soulmaz dedicates most of her practice to all areas of Immigration Law, with a focus on removal defense. Soulmaz is a dedicated, passionate and aggressive attorney with vast experience in representing clients in criminal and traffic matters in several counties through the Commonwealth. With her experience, Soulmaz understands the immigration consequences of criminal and traffic dispositions in Virginia.            </p>
            <p>Soulmaz’s family emigrated to the United States from Iran in the 1980s, which in part, helped cultivate her desire to use her education to help individuals and families navigate our legal system efficiently and effectively. Soulmaz graduated with honors from the North Carolina Central University School of Law in Durham, N.C. Soulmaz, who is a native of Richmond, received her bachelors degree in International Relations and Economics from Virginia Commonwealth University, and subsequently received a masters degree in Middle Eastern Studies from the University of Virginia. Soulmaz also spent a summer abroad at a university in Cairo, Egypt, where she studied Arabic and International Business.</p>
            <p>During law school, Soulmaz served as a student clerk for the Honorable Judge Herbert B. Dixon, Jr.  while he presided over the Felony I Calendar at The Superior Court of the District of Columbia in Washington, D.C. She also served as a student attorney in the criminal defense clinic, where she represented individuals who had been charged with misdemeanor offenses. While a student, Soulmaz also had the rare distinction of publishing a scholarly article. Her submission, “Montes-Lopez v. Holder: Applying Eldridge to Ensure a Per Se Right to Counsel for Indigent Immigrants in Removal Proceedings,” was published in May 2014.</p>
            <p>Before joining partner Raul Novo, Soulmaz worked for almost three years at Fayad Law, P.C.’s Richmond, Virginia office. Today, Soulmaz has immense experience in preparing and filing defensive reliefs and motions before Immigration Courts and Board of Immigration Appeals, including, Asylum, Cancellation of Removal, Prosecutorial Discretion requests, Convention against Torture, I-212(h) Criminal and Inadmissibility Waivers, and I-601A/I-601 Provisional Waivers. Soulmaz has represented individuals in Individual, Master Calendar and Bond Hearings before various Immigration Courts. She has experience in preparing and filing humanitarian and family-based immigration petitions, applications, briefs and waivers for USCIS, including Naturalization and Adjustment of Status applications. Well-versed in state and federal appeals, Soulmaz single-handedly gave oral arguments before a three-panel judge at the United States Court of Appeals for the Fourth Circuit, arguing for procedural due process rights in a contested alleged immigration marriage fraud case in Bassam Hanna v. Loretta Lynch on March 21, 2016.</p>
            Soulmaz is a member of both the Virginia and District of Columbia Bar Associations.',
    'img' => asset('img/mejor-abogado-en-chesterfield.webp'),
    'img_alt' => 'Mejor abogado en chesterfield',
];