<?php

return [

    'content'=>'<h2 class="blue_title">Términos y Condiciones</h2>
            <p>Este sitio web y la información contenida aquí han sido preparados por Novo Taghavi, (La Firma) LTD en Richmond, Virginia., sólo con fines informativos y no constituye asesoramiento jurídico. Esta información no tiene la intención de crear, ni su recepción constituye una relación de abogado-cliente. Los espectadores no deben actuar de acuerdo con la información aquí encontrada sin buscar asesoría legal.</p>
            <p>La Firma está comprometida con la protección de su privacidad, y tratará toda la información que proporcione a través del sitio web de la Firma, incluyendo su información de registro, con el mayor respeto. La Firma trabaja diligentemente para asegurar que ha tomado todas las medidas administrativas y técnicas apropiadas para prevenir el uso no autorizado o ilegal de su información de identificación personal, y para prevenir cualquier pérdida o destrucción accidental, o daño a dicha información. La Firma no vendrá ni revelará información personal identificable sobre usted a terceros no afiliados excepto de acuerdo con esta “Política de Privacidad”.</p>
            <h5 class="bold_text">Obtención de Información.</h5>
            <p>1. El sitio web de La Firma recopila cierta información sobre los visitantes, incluso cuando no están conectados. La Firma puede recopilar su dirección de IP, el URL de los sitios web que visita (antes, durante y después de visitar el sitio web de la Firma), los tiempos y fechas de las visitas, información sobre el hardware y software de la computadora que use y otra información que puede estar disponible. También, La Firma puede colocar “cookies” en su computadora para reconocerlo en visitas posteriores para permitir que La Firma mejore su experiencia de navegación, así como recopilar información sobre usted. Puede ajustar la configuración de su navegador o usar otros medios para prevenir que las cookies sean colocadas en su computadora, pero hacerlo puede resultar en reducción de funcionalidad y en una experiencia de navegación menos personalizada.</p>
            <p>2. La Firma puede pedirle que proporcione cierta información adicional sobre usted, incluyendo su nombre, información de contacto, la organización de la que proviene y otro tipo de información que La Firma puede usar para identificarlo. Si usted elige no proporcionar dicha información, puede no permitirle acceder a ciertas funciones del sitio web de La Firma, contenidos o servicios.</p>
            <h5 class="bold_text">Uso de Información.</h5>
            <p>1. La Firma usa la información que recopila sobre usted para mejorar su experiencia de navegación, personalizando los sitios web de La Firma a su interés, y también para ayudar a La Firma a seleccionar el contenido y los servicios que pueden resultar interesantes y útiles. La información sobre el contenido que visita y los servicios que usa pueden utilizarse solos o junto con información recopilada de otros usuarios para ayudar a La Firma a adaptar el sitio Web de La Firma y sus otros productos y servicios para satisfacer mejor las necesidades e intereses de usted y otros usuarios.</p>
            <p>2. La información que usted proporcione también puede ser utilizada como parte del esfuerzo de La Firma de mantenerlo informado sobre eventos y productos seleccionados y servicios que pueden ser de su interés. En algunos casos, La Firma puede contactarlo con información de terceros para tales fines. En otros casos, su información podría ser compartida con un tercero de acuerdo a un proceso que contempla tal intercambio, pero que usted conscientemente inició.</p>
            <p>3. La Firma se reserva el derecho de revelar cualquier información que obtenga a través del sitio web de La Firma a las autoridades gubernamentales o reguladoras apropiadas, si así lo requiere la ley o cualquier agencia gubernamental.</p>
            <h5 class="bold_text">Transferencias de Información.</h5>
            <p>Periódicamente, La Firma puede revelar información sobre usted a proveedores de servicios cuidadosamente seleccionados que La Firma puede contratar para hospedar el sitio web de La Firma o para proporcionar otros servicios. La Firma requerirá que todos los proveedores de servicios utilicen la información únicamente para proporcionar los servicios especificados, y de lo contrario, cumplir con los requisitos de esta Política de Servicios. Excepto según lo dispuesto en esta Política de Privacidad, La Firma no proporcionará su información a terceros para ningún otro propósito, incluyendo la comercialización.</p>
      
            <h5 class="bold_text">Información Enviada A través del Sitio Web No Es Segura</h5>
            <p>Cualquier información enviada a La Firma por correo electrónico de internet o a través del sitio web no es segura y se hace de manera no confidencial. Cualquier información que envíe a La Firma a través de internet, ya sea a través del sitio web de La Firma o por correo electrónico, se hace bajo su propio riesgo.</p>
            <h5 class="bold_text">Enviar Información No Forma Una Relación Entre Abogado y Cliente</h5>
            <p>La transmisión de información hacia y desde este sitio web no crea una relación abogado-cliente entre usted y La Firma, ni tiene la intención de hacerlo. La transmisión del sitio web, en parte o en su totalidad, y/o cualquier comunicación con nosotros vía correo electrónico a través de internet mediante este sitio, no constituye ni crea una relación abogado-cliente entre nosotros y cualquier destinatario.</p>
            '

];
